fix for Meraki parsing errors #85
Cargill/OpenSIEM-Logstash-Parsing pull request #160
Opened 2021-10-27 13:35 UTC by badalkumar1223

fix for Meraki parsing errors #85

PR: https://github.com/Cargill/OpenSIEM-Logstash-Parsing/issues/85

2021-11-29 14:02 UTC, Akhila-Y requested changes

2021-11-29 14:02 UTC, Akhila-Y commented on config/processors/syslog_log_audit_spectracom.ntp.conf
> +  else if [actual_msg] =~ "xo1" or [actual_msg] =~ "XO1" {
this can be done with | operator --> else if [actual_msg] =~ "xo1|XO1"

2021-11-29 14:02 UTC, Akhila-Y commented on config/processors/syslog_log_security_cisco.meraki.fw.conf
> +        rest_msg1 => "%{?data}pattern: %{event.action}"
this should be "rest_msg"

2021-12-09 13:31 UTC, KrishnanandSingh commented
Closing in favour of #197

2021-12-09 13:31 UTC, closed without merging