log.source.hostname changes in log-sources.
Cargill/OpenSIEM-Logstash-Parsing pull request #178
Opened 2021-11-17 08:42 UTC by badalkumar1223

## Description
log.source.hostname changes in log-sources.

2021-11-29 15:59 UTC, Akhila-Y requested changes

2021-11-29 15:59 UTC, Akhila-Y commented on config/processors/logstash_virtustream_linux_forwarder.conf
> +  # mutate { gsub => ['source.port','[}]','']}
you can remove the commented block

2021-11-29 15:59 UTC, Akhila-Y commented on config/processors/logstash_virtustream_linux_forwarder.conf
> +    copy => {"event.module" => "log.source.hostname"}
reason why event.module being copied to log.source.hostname??

2021-11-29 15:59 UTC, Akhila-Y commented on config/processors/api_log_audit_aws.ghe.conf
> +    rename => { "[tmp][host]" => "log.source.hostname" }
Badal, could you take updated version and then make the same changes with nested notation?

2021-12-01 09:05 UTC, KrishnanandSingh commented
Closing this in favor of #194

2021-12-01 09:05 UTC, closed without merging