Cisco IOS (cisco.router and cisco.switch) new rules
Cargill/OpenSIEM-Logstash-Parsing pull request #24
Opened 2021-05-20 16:54 UTC by nnovaes

## Description

new parsing rules for cisco.router and cisco.switch. The old version of this processor needs some rework. However, there are functioning bits of it that i have preserved, since they kind of work. the new rules provide some good foundation for future "full" parsing and also covers bgp and interface up/down msgs. the lookup database for translate filters is static.

2021-05-20 19:51 UTC, nnovaes commented
@brian-grabau @verbecee 
 I have moved the interface fields under observer, however i don't necessarily agree these fields should be there. i've updated https://github.com/elastic/ecs/issues/610 with this issue, others have been discussing as well. perhaps if/when it gets resolved we should revisit this field mapping.

2021-05-24 15:47 UTC, KrishnanandSingh requested changes
Indentations are not uniform. Please use 2 spaces to indent everywhere.

2021-05-28 15:53 UTC, nnovaes commented on config/processors/syslog_log_audit_cisco.router.conf
> +          "%{GREEDYDATA:[tmp][ingest_timestamp]}\s\{name=%{GREEDYDATA:[tmp][logsource]}\}\s<%{NUMBER:syslog_pri}>%{NUMBER:[event.id]}:\s%{GREEDYDATA:[tmp][device_timestamp]}:\s\%%{WORD:[tmp][facility
@KrishnanandSingh ,

If we are parsing all syslog pri headers but not removing them from the message for the downstream filters (which makes sense) , i believe it is still relevant to have those fields in groks/dissects throughout configs, however we'd need to change the field the grok captures it, so in this case i'll need to replace <%{NUMBER:syslog_pri}> with <%{NUMBER}>. i'll make that change

2021-06-02 18:04 UTC, nnovaes commented on config/processors/syslog_log_audit_cisco.router.conf
> +          "%{GREEDYDATA:[tmp][ingest_timestamp]}\s\{name=%{GREEDYDATA:[tmp][logsource]}\}\s<%{NUMBER:syslog_pri}>%{NUMBER:[event.id]}:\s%{GREEDYDATA:[tmp][device_timestamp]}:\s\%%{WORD:[tmp][facility
done. removed in #4899c1d

2021-06-02 18:58 UTC, nnovaes commented
@KrishnanandSingh  ready to merge

2021-06-03 11:44 UTC, KrishnanandSingh approved these changes

2021-06-03 11:44 UTC, KrishnanandSingh commented on config/processors/syslog_log_audit_cisco.router.conf
>      # log.source.hostname does not exist in ECS. this field comes from the relay. because it may break something we'll just copy it to the proper field name before someone addresses it
this comment should be removed now as we are not copying it.

2021-06-03 11:44 UTC, merged